---
title: "Gapminder Exercise Template"
author: "Bora Jin"
date: "`r Sys.Date()`"
output: github_document
---

```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 7)
```


## Load packages
```{r LoadLibrary, message=FALSE}
library(tidyverse)
```

## Load data
```{r ReadTable, message=FALSE}
gap = read_csv("https://bit.ly/gap_data")
```

## Exercises

### Exercise 1

How many observations are in this dataset?

There are `r nrow(gap)` observations in the dataset. 

### Exercise 2

Visualize the relationship between GDP and life expectancy for 
countries in Europe in 1952 using a scatter plot.

```{r eu_52, echo=FALSE}
eu_52 = gap %>% filter(continent == "Europe", year == 1952)
ggplot(data = eu_52, aes(x = gdpPercap, y = lifeExp))+geom_point()
```

### Exercise 3

Add year 1967 in another color.

```{r eu_52_67, echo=FALSE}
ggplot()+geom_point(data=eu_52, aes(x = gdpPercap, y = lifeExp))+geom_point(data=gap %>% filter(continent == "Europe", year == 1967), aes(x = gdpPercap, y = lifeExp), colour = "red")
```

